# Utiliser l'image Jenkins comme image de base
FROM jenkins/jenkins:lts

# Passer en utilisateur root pour installer les dépendances
USER root

# Installer les prérequis et Docker
RUN apt-get update -y && \
    apt-get install -y apt-transport-https ca-certificates curl gnupg && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && \
    chmod a+r /etc/apt/keyrings/docker.asc && \
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo $VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update -y && \
    apt-get install -y docker-ce docker-ce-cli containerd.io unzip && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip" && \
    unzip /tmp/awscliv2.zip -d /tmp && \
    /tmp/aws/install && \
    rm -rf /tmp/awscliv2.zip /tmp/aws && \
    apt-get clean

# Ajouter l'utilisateur Jenkins au groupe Docker (le créer s'il n'existe pas)
RUN groupadd -f docker && \
    usermod -aG docker jenkins

# Créer le répertoire Docker et le volume pour DinD
RUN mkdir -p /var/lib/docker
VOLUME /var/lib/docker

# Revenir à l'utilisateur Jenkins
USER jenkins